[package]
name = "bucl"
version = "0.1.0"
edition = "2021"
description = "Parser and executor for the BUCL programming language"
license = "MPL-2.0"

[[bin]]
name = "bucl"
path = "src/main.rs"

[dependencies]
rand = "0.8"
